# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerHub'
        repository: 'emmanuelpereira/ademir-mine-admin'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          latest
          $(tag)
    
    - task: SSH@0
      displayName: Update Docker Digital Ocean
      inputs:
        sshEndpoint: 'SSH VPS'
        runOptions: 'commands'
        commands: |
          docker ps -a | grep 'ademir-mine' && docker rm -f --volumes ademir-mine || true
          docker images -f "dangling=true" -q
          docker system prune --force
          docker pull emmanuelpereira/ademir-mine-admin:$(tag)
          docker run --name=ademir-mine --restart=always -v /var/ademir-mine/.env:/App/.env -d emmanuelpereira/ademir-mine-admin:$(tag)
        readyTimeout: '20000'
